"""initial_tables

Revision ID: 9ba05a291bda
Revises: 
Create Date: 2026-06-22 09:27:06.367396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba05a291bda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_major', sa.Integer(), nullable=False),
    sa.Column('version_minor', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('checksum_algorithm', sa.String(length=10), nullable=True),
    sa.Column('sync_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_major', 'version_minor', name='uq_catalog_version')
    )
    op.create_index('idx_versions_checksum', 'catalog_versions', ['checksum'], unique=True)
    op.create_index('idx_versions_status', 'catalog_versions', ['status'], unique=False)
    op.create_index(op.f('ix_catalog_versions_checksum'), 'catalog_versions', ['checksum'], unique=True)
    op.create_table('equipments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_equipments_slug', 'equipments', ['slug'], unique=False)
    op.create_index(op.f('ix_equipments_name'), 'equipments', ['name'], unique=True)
    op.create_index(op.f('ix_equipments_slug'), 'equipments', ['slug'], unique=True)
    op.create_table('movement_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_movement_groups_order', 'movement_groups', ['order_index'], unique=False)
    op.create_index('idx_movement_groups_slug', 'movement_groups', ['slug'], unique=False)
    op.create_index(op.f('ix_movement_groups_name'), 'movement_groups', ['name'], unique=True)
    op.create_index(op.f('ix_movement_groups_order_index'), 'movement_groups', ['order_index'], unique=False)
    op.create_index(op.f('ix_movement_groups_slug'), 'movement_groups', ['slug'], unique=True)
    op.create_table('muscle_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_muscle_groups_order', 'muscle_groups', ['order_index'], unique=False)
    op.create_index('idx_muscle_groups_slug', 'muscle_groups', ['slug'], unique=False)
    op.create_index(op.f('ix_muscle_groups_name'), 'muscle_groups', ['name'], unique=True)
    op.create_index(op.f('ix_muscle_groups_order_index'), 'muscle_groups', ['order_index'], unique=False)
    op.create_index(op.f('ix_muscle_groups_slug'), 'muscle_groups', ['slug'], unique=True)
    op.create_table('exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('execution_tips', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('target_muscle_primary', sa.String(length=100), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('gif_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('movement_group_id', sa.Uuid(), nullable=False),
    sa.Column('muscle_group_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movement_group_id'], ['movement_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uix_exercises_slug')
    )
    op.create_index('idx_exercises_movement_group_id', 'exercises', ['movement_group_id'], unique=False)
    op.create_index('idx_exercises_muscle_group_id', 'exercises', ['muscle_group_id'], unique=False)
    op.create_index('idx_exercises_name', 'exercises', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_movement_group_id'), 'exercises', ['movement_group_id'], unique=False)
    op.create_index(op.f('ix_exercises_muscle_group_id'), 'exercises', ['muscle_group_id'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_index(op.f('ix_exercises_slug'), 'exercises', ['slug'], unique=True)
    op.create_table('exercise_alternatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('alternative_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['alternative_exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alternatives_alt_exercise_id', 'exercise_alternatives', ['alternative_exercise_id'], unique=False)
    op.create_index('idx_alternatives_exercise_id', 'exercise_alternatives', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_alternatives_alternative_exercise_id'), 'exercise_alternatives', ['alternative_exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_alternatives_exercise_id'), 'exercise_alternatives', ['exercise_id'], unique=False)
    op.create_table('exercise_equipments',
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('usage_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id', 'equipment_id')
    )
    op.create_table('exercise_instructions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_instructions_step_order', 'exercise_instructions', ['exercise_id', 'step_order'], unique=False)
    op.create_index(op.f('ix_exercise_instructions_exercise_id'), 'exercise_instructions', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_instructions_step_order'), 'exercise_instructions', ['step_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_instructions_step_order'), table_name='exercise_instructions')
    op.drop_index(op.f('ix_exercise_instructions_exercise_id'), table_name='exercise_instructions')
    op.drop_index('idx_instructions_step_order', table_name='exercise_instructions')
    op.drop_table('exercise_instructions')
    op.drop_table('exercise_equipments')
    op.drop_index(op.f('ix_exercise_alternatives_exercise_id'), table_name='exercise_alternatives')
    op.drop_index(op.f('ix_exercise_alternatives_alternative_exercise_id'), table_name='exercise_alternatives')
    op.drop_index('idx_alternatives_exercise_id', table_name='exercise_alternatives')
    op.drop_index('idx_alternatives_alt_exercise_id', table_name='exercise_alternatives')
    op.drop_table('exercise_alternatives')
    op.drop_index(op.f('ix_exercises_slug'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_muscle_group_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_movement_group_id'), table_name='exercises')
    op.drop_index('idx_exercises_name', table_name='exercises')
    op.drop_index('idx_exercises_muscle_group_id', table_name='exercises')
    op.drop_index('idx_exercises_movement_group_id', table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_muscle_groups_slug'), table_name='muscle_groups')
    op.drop_index(op.f('ix_muscle_groups_order_index'), table_name='muscle_groups')
    op.drop_index(op.f('ix_muscle_groups_name'), table_name='muscle_groups')
    op.drop_index('idx_muscle_groups_slug', table_name='muscle_groups')
    op.drop_index('idx_muscle_groups_order', table_name='muscle_groups')
    op.drop_table('muscle_groups')
    op.drop_index(op.f('ix_movement_groups_slug'), table_name='movement_groups')
    op.drop_index(op.f('ix_movement_groups_order_index'), table_name='movement_groups')
    op.drop_index(op.f('ix_movement_groups_name'), table_name='movement_groups')
    op.drop_index('idx_movement_groups_slug', table_name='movement_groups')
    op.drop_index('idx_movement_groups_order', table_name='movement_groups')
    op.drop_table('movement_groups')
    op.drop_index(op.f('ix_equipments_slug'), table_name='equipments')
    op.drop_index(op.f('ix_equipments_name'), table_name='equipments')
    op.drop_index('idx_equipments_slug', table_name='equipments')
    op.drop_table('equipments')
    op.drop_index(op.f('ix_catalog_versions_checksum'), table_name='catalog_versions')
    op.drop_index('idx_versions_status', table_name='catalog_versions')
    op.drop_index('idx_versions_checksum', table_name='catalog_versions')
    op.drop_table('catalog_versions')
    # ### end Alembic commands ###
